### ISSUE TITLE
Windows Version - doesn't start - incorrect JDK/JRE 

### ISSUE THREAD

**Issue by EricGT** [RuleWorld/rulebender#209]
When using RuleBender 2.2.1 installed from [BioNetGen ](http://www.csb.pitt.edu/Faculty/Faeder/?page_id=409) site for Windows 10 [64-bit](http://www.csb.pitt.edu/Faculty/Faeder/?sdm_downloads=rulebender-2-3-1-for-win64) version various errors can occur related to the JRE/JDK installation.

![rulebender_error_001](https://user-images.githubusercontent.com/2372050/36861018-dd5ba3da-1d50-11e8-9f0a-ef5ee4f747bf.png)

> An error has occurred. See the log file ...\RuleBender-workspace\.metadata\.log

RuleBender-workspace\.metadata\.log

**java.version=9.0.1**
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -consoleLog -data @noDefault

!ENTRY org.eclipse.osgi 4 0 2018-02-25 14:30:59.985
!MESSAGE Application error
!STACK 1
java.lang.NoClassDefFoundError: org/w3c/dom/stylesheets/StyleSheet
	at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngineManager.getCSSSWTEngine(ThemeEngineManager.java:41)
	at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngineManager.getEngineForDisplay(ThemeEngineManager.java:30)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createThemeEngine(PartRenderingEngine.java:1428)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.initializeStyling(PartRenderingEngine.java:1281)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1036)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at rulebender.Application.start(Application.java:87)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.stylesheets.StyleSheet cannot be found by org.eclipse.e4.ui.css.core_0.10.100.v20140424-2042
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 26 more

![rulebender_error_002](https://user-images.githubusercontent.com/2372050/36861026-e192c83e-1d50-11e8-899e-9198f9378a98.png)

> A Java Runtime Environment (JRE) or Java Development Kit (JDK) must be available in order to run RuleBender. No Java virtual machine ws found after searching the following location: C:\...\RuleBender-2.2.1-win64\jre\bin\java.exe
> java.exe in your current PATH

![rulebender_error_003](https://user-images.githubusercontent.com/2372050/36861032-e4f3233e-1d50-11e8-91cc-9730679aac38.png)

> To run properly, RuleBender requires Java version 1.8. Currently our system is running 1.7.0_80. This may be sufficient for doing simulations, but the visualization tools likely will not function unless Java is upgraded. More information is available at bionetgent.org in the Download section.

**Comment by EricGT** [comment]
The solution to all three errors is to provide RuleBender 2.2.1 with [Java SE Runtime Environment 8u161 (JRE)](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html)

Download re-8u161-windows-x64.tar.gz
Uncompress the file.
Copy the directory **jre1.8.0_161** to **RuleBender-2.2.1-win64**
Rename directory  **jre1.8.0_161** to **jre**
Start RuleBender

**Comment by jrfaeder** [comment]
Thanks for the post Eric! We will get the JRE into the next RB release so we don't have this problem in the future.
